--ex01
SELECT 
COUNTRY.CONTINENT,
FLOOR(AVG(CITY.POPULATION))
FROM CITY 
INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
GROUP BY COUNTRY.CONTINENT;

--ex02
SELECT
ROUND(CAST(SUM(CASE
 WHEN a.signup_action = 'Confirmed' THEN 1
 ELSE 0
END) AS DECIMAL)
/ COUNT(a.signup_action),2)
FROM texts AS a  
LEFT JOIN emails AS b  
ON a.email_id = b.email_id
WHERE NOT b.email_id IS NULL;

